ipaadmin_password: "{{ freeipa.admin_password }}"
ipaserver_domain: "{{ freeipa.domain }}"
ipaserver_realm: "{{ freeipa.realm }}"
ipaclient_servers:
  - "{{ freeipa.server }}"
ipaadmin_principal: "admin"