ipaadmin_password: "{{ freeipa.admin_password }}"
ipadm_password: "{{ freeipa.admin_password }}"
ipaserver_domain: "{{ freeipa.domain }}"
ipaserver_realm: "{{ freeipa.realm }}"
ipaserver_setup_firewalld: no
ipaserver_setup_dns: yes
ipaserver_allow_zone_overlap: yes
ipaserver_ip_addresses:
  - "{{ ansible_default_ipv4.address }}"
ipaserver_forwarders:
  - 1.1.1.1
  - 8.8.8.8
ipaserver_no_ui_redirect: yes
ipaserver_no_host_dns: yes