---

- name: Ensure keycloak dir
  become: yes
  file:
    path: "{{ mount }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- become: yes
  copy:
    content: "{{ keycloak.realm }}"
    dest: "{{ mount }}/realm.json"
    mode: 0755

- docker_container:
    name: keycloak
    image: uccnetsoc/keycloak:9.0.3-themed
    recreate: yes
    env:
      DB_VENDOR: h2
      KEYCLOAK_USER: "{{ keycloak.username }}"
      KEYCLOAK_PASSWORD: "{{ keycloak.password }}"
      KEYCLOAK_IMPORT: "/tmp/keycloak/realm.json"
      KEYCLOAK_FRONTEND_URL: "{{ keycloak.hostname }}"
    hostname: "{{ keycloak.hostname }}"
    restart_policy: on-failure
    ports:
      - "8080:8080"
    volumes:
      - "{{ mount }}/:/tmp/keycloak/"
      - "/etc/localtime:/etc/localtime:ro"
      # - "./backing-services/keycloak/krb5.keytab:/krb5.keytab"
      # - "./backing-services/keycloak/themes/admin:/opt/jboss/keycloak/themes/admin"
