- name: ssh
  import_playbook: requisite-ubuntu.yml

- name: Install Dev Tools
  hosts: container
  become: yes
  tasks:
    - name: Install Dependencies
      apt:
        name:
          - git
          - jq
          - gcc
          - sqlite
          - gdb
          - gnupg
          - clang
          - ruby
          - python
          - vim
          - emacs
          - curl
          - software-properties-common
          - gradle
          - mercurial
          - composer
          - ipython3
          - python-mysqldb
          - python3-keras
          - mysql-client
          - make


    - name: Add node PPA
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install nodejs
      apt:
        name: nodejs
        update_cache: yes

    - name: Add golang PPA
      shell: add-apt-repository ppa:longsleep/golang-backports

    - name: Install golang
      apt:
        name: golang-go
        update_cache: yes

    - name: Install rustup
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Install NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

    - name: Install Helm
      shell: curl -o- https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Ensure /etc/docker
      file:
        path: /etc/docker
        state: directory

    - name: Ensure /etc/docker/daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "storage-driver": "overlay2"
          }

    - name: Ensure Docker dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        install_recommends: no
        update_cache: yes

    - name: Ensure Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Ensure Docker APT repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Ensure Docker
      apt: 
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker Compose dependencies
      apt:
        name: python3-pip
        state: latest

    - name: Ensure Docker Compose
      pip:
        name: docker-compose
        state: latest

    - name: Ensure Docker Py
      pip:
        name: docker
        state: latest

    - name: Reload Docker daemon
      systemd:
        state: enabled
        daemon_reload: no
        name: docker