- name: Install Dev Tools
  hosts: container
  become: yes
  tasks:
    - name: Install Dependencies
      apt: 
        name: 
          - git
          - jq
          - gcc
          - sqlite
          - gdb
          - gnupg
          - clang
          - ruby
          - python
          - vim
          - emacs
          - curl
          - software-properties-common

    - name: Add node PPA
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install nodejs
      apt: 
        name: nodejs
        update_cache: yes
        
    - name: Add golang PPA
      shell: add-apt-repository ppa:longsleep/golang-backports

    - name: Install golang
      apt: 
        name: golang-go
        update_cache: yes

    - name: Install rustup
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y