- name: Install MEAN stack
  hosts: container
  become: yes
  tasks:
    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install npm
      raw: apt-get install -y npm
      args:
        executable: /bin/bash

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install mongodb keys 
      shell: curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add - 

    - name: Install mongodb repo
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list

    - name: Install mongodb
      apt:
        name: mongodb-org
        update_cache: yes

    - name: Enable mongo service
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name:  mongod

    - name: Install Angular CLI
      npm:
        name: "@angular/cli"
        global: yes

      ignore_errors: yes
    - name: Install Express globally for cache
      npm:
        name: express
        global: yes
      ignore_errors: yes
