- name: ssh
  import_playbook: requisite-ubuntu.yml

- name: Install Node
  hosts: container
  become: yes
  tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - git
        - curl

    # Special handling for npm
    - name: Install npm
      raw: apt-get install -y npm
      args:
        executable: /bin/bash

    # Yarn for good measure
    - name: Install Yarn
      shell: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update && sudo apt install yarn