- name: Install SSH
  hosts: container
  tasks:
    - apt:
        name: openssh-server
        state: present
    - service:
        name: ssh
        enabled: yes
    - copy:
        dest: /etc/ssh/sshd_config.d/login.conf
        mode: 0770
        content: PermitRootLogin yes
    - service:
        name: systemd-resolved
        enabled: no
        state: stopped
    - copy:
        dest: /etc/resolv.conf
        content: |
            nameserver 1.1.1.1