---
- name: "Ensure base install"
  hosts: non_sudo

  # Assume we're doing a completely new install from a fresh server
  # Fact gathering requires python, which the server may not have
  gather_facts: no
  
  roles:
    - ansible-requirements  # Installs python2.7, 3 and then gathers facts
    # - ubuntu-universe     # Ubuntu community repos. Uncomment when every server is on 18.04
    - essential-utils       # pip, iotop, htop, git, node, etc...
    - netsoc-neo-dir        # Set's up /netsoc-neo/ for storing our central files
    - shells
    - fail2ban
    - docker                # Docker APT, Docker, etc...
    - apt-autoremove        # Clean up any unused deps