---
- name: Ensure Drone Server, Agent and DB
  hosts: boole
  vars_files:
    - vars/ci.yml
    - vars/discord.yml
    - vars/mysql_server_legacy.yml
    - vars/vault.yml
    - vars/secrets_legacy.yml
  roles:
  - ci