
- name: "Deploy Traefik, Netsoc.co, Netsoc Blog, Netsoc Wiki"
  hosts: bigbertha
  pre_tasks:
    - name: Ensure Traefik
      include_playbook: traefik.yml
  roles:
    - netsoc.co
    - blog.netsoc.co
    - wiki.netsoc.co
  vars_files:
    - vars/cloudflare.yml  # traefik certs
    - vars/docker_registry.yml # netsoc.co image
    - vars/mysql_server.yml # mysql server root
    - vars/wiki.yml
    - vars/ldap.yml
    - vars/secrets.yml
  tags:
    - install-base
    - install-swarm
    - install-swarm-services

- name: "Deploy NetsocAdmin2"
  hosts: bigbertha # it says bertha but the constraint inside the role restricts it to leela
  roles:
    - netsocadmin2
  vars_files:
    - vars/cloudflare.yml  # traefik certs
    - vars/docker_registry.yml # netsoc.co image
    - vars/mysql_server.yml # mysql server root
    - vars/wiki.yml
    - vars/ldap.yml
    - vars/secrets.yml
  tags:
    - install-base
    - install-swarm
    - install-swarm-services