---

- name: "Ensure Portal server"
  hosts: lovelace
  roles:
    - role: proxmox-infra-cloudinit-vm
      vars:
        vm:
          recreate: yes
          name: "portal.vm.netsoc.co"
          clone_qcow2: "https://cloud-images.ubuntu.com/releases/focal/release-20200907/ubuntu-20.04-server-cloudimg-amd64.img"
          clone_qcow2_hash: sha256:995771784f85305ef7e9b779f0f39dde6a0e59b50914c316a9ae8b039cb4c52e
          net:
            net0: "virtio,bridge=vmbr0,tag={{ interfaces.portal.net0_tag }}"
          disks:
            virtio0:
              pool: local-lvm
              definition: "40,format=raw"
          cores: 4
          memory: 2048
          description:
            groups:
              - vm
              - portal
              - ipaclients
              - gluster
              - gluster_client
              - gluster_client_allowed_mount_homedirs
            host_vars:
              ansible_ssh_private_key_file: "./keys/portal/id_rsa"
        cloudinit:
          drive_device: ide2
          userdata: |
            #cloud-config
            preserve_hostname: false
            manage_etc_hosts: true
            fqdn: portal.vm.netsoc.co
            packages:
              - qemu-guest-agent
            runcmd:
              - [ systemctl, enable, qemu-guest-agent ]
              - [ systemctl, start, qemu-guest-agent, --no-block ]
            users:
              - name: netsoc
                gecos: Netsoc Management User
                primary_group: netsoc
                groups: netsoc
                shell: /bin/bash
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - "{{ lookup('file', './keys/portal/id_rsa.pub') }}"
            apt: 
              preserve_sources_list: true
              primary:
                - arches: [default]
                  uri: http://ie.archive.ubuntu.com/ubuntu/
              security:
                - uri: http://security.ubuntu.com/ubuntu
          networkconfig: 
            version: 2
            ethernets:
              ens18: "{{ interfaces.portal.net0 }}"
        wait_for_ssh_ip: "{{ interfaces.portal.net0.addresses[0] }}"
  vars_files:
    - vars/network.yml
    - vars/proxmox.yml
    - vars/secrets.yml

- name: "Reload inventory to pull new VMs"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - meta: refresh_inventory
