---
- name: "Ensure games server"
  hosts: proxmox_hosts,!control,!feynman # To be changed -- remove feynman, leave control
  roles:
    - role: proxmox-infra-cloudinit-vm
      vars:
        vm:
          name: "games{{ ansible_play_hosts_all.index( inventory_hostname ) }}.vm.netsoc.co"
          clone: "netsoc-ubuntu-server-{{ inventory_hostname }}"
          net:
            net0: "virtio,bridge=vmbr0,tag=30"
          disks:
            virtio0:
              resize: "10G" # To be changed
            virtio1:
              pool: local-lvm
              definition: "100,format=raw"
          cores: 4
          memory: 8192 # To be changed
          description:
            groups:
              - vm
              - games
              - prometheus_base
              - prometheus_docker
              - ipaclients
            host_vars:
              ansible_ssh_private_key_file: "./keys/games/id_rsa"
        cloudinit:
          drive_device: ide2
          userdata: |
            #cloud-config
            users:
              - name: netsoc
                gecos: Netsoc Management User
                primary_group: netsoc
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - {{ lookup('file', './keys/games/id_rsa.pub') }}
            preserve_hostname: false
            manage_etc_hosts: true
            fqdn: games{{ ansible_play_hosts_all.index(inventory_hostname) }}.vm.netsoc.co
          networkconfig: 
            version: 2
            ethernets:
              ens18:
                addresses:
                  - "{{ interfaces.gamesN.net0.addresses[0] | ipmath(ansible_play_hosts_all.index(inventory_hostname)) }}/24"
                gateway4: "{{ interfaces.gamesN.net0.gateway4 }}"
                nameservers: "{{ interfaces.gamesN.net0.nameservers }}"
                optional: true
        wait_for_ssh_ip: "{{ interfaces.games.net0.addresses[0] }}"
  vars_files:
    - vars/network.yml
    - vars/proxmox.yml
    - vars/secrets.yml

- name: "Reload inventory to pull new VMs"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - meta: refresh_inventory
