---

- name: "INFRA - Ensure web server"
  hosts: lovelace
  roles:
    - role: proxmox-cloudinit-vm
      vars:
        vm:
          name: "web.infra.netsoc.co"
          clone:
            pool: local
            qcow2_url: "https://cloud-images.ubuntu.com/releases/focal/release-20200921.1/ubuntu-20.04-server-cloudimg-amd64.img"
            qcow2_hash: sha256:d18a9d2b890d3c1401e70a281cae44b61816aa669c4936f7a99c168e572ec8cb
          cores: 4
          memory: 12288
          description:
            groups:
              - vm
              - web
              - fluentd
              - prometheus_base
              - prometheus_docker
              - ipaclients
            host_vars:
              ansible_ssh_private_key_file: "./keys/infra/web/id_rsa"
          net:
            net0: "virtio={{ interfaces.infra.web.net0.match.macaddress }},tag={{ vlan.infra }},bridge={{ vmbr }}"
            net1: "virtio={{ interfaces.infra.web.net1.match.macaddress }},tag={{ vlan.wan }},bridge={{ vmbr }}"
          disks:
            pool: local-lvm
            boot:
              size: 30G
              format: raw
            extra:
              - size: 45G
                format: raw
          efi:
            pool: local
          cloudinit:
            pool: local
            force: yes
            userdata: |
              #cloud-config
              preserve_hostname: false
              manage_etc_hosts: true
              fqdn: web.infra.netsoc.co
              packages:
                - qemu-guest-agent
              runcmd:
                - [ systemctl, enable, qemu-guest-agent ]
                - [ systemctl, start, qemu-guest-agent, --no-block ]  
              users:
                - name: netsoc
                  gecos: Netsoc Management User
                  primary_group: netsoc
                  groups: netsoc
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "{{ lookup('file', './keys/infra/web/id_rsa.pub') }}"
              apt: 
                preserve_sources_list: true
                primary:
                  - arches: [default]
                    uri: http://ie.archive.ubuntu.com/ubuntu/
                security:
                  - uri: http://security.ubuntu.com/ubuntu
              disk_setup:
                /dev/vdb:
                  table_type: 'gpt'
                  layout:
                    - [100,83] # 100% Linux fs
                  overwrite: false
              fs_setup:
                - label: data-disk
                  filesystem: ext4
                  device: '/dev/vdb1'
                  overwrite: false
              mounts:
                - [ vdb, /netsoc, auto ]
            networkconfig: 
              version: 2
              ethernets: "{{ interfaces.infra.web }}"
          wait_for_ssh_ip: "{{ interfaces.infra.web.net0.addresses[0] }}"
  vars_files:
    - vars/network.yml
    - vars/secrets_mapping.yml
    - vars/secrets.yml

- name: "Reload inventory to pull new VMs"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - meta: refresh_inventory
