- name: "Ensure NFS server"
  hosts: lovelace
  roles:
    - role: proxmox-infra-cloudinit-vm
      vars:
        vm:
          name: "nfs.vm.netsoc.co"
          clone: "netsoc-ubuntu-server-{{ inventory_hostname }}"
          net:
            net0: "virtio,bridge=vmbr0,tag=30"
          disks:
            virtio0:
              resize: "20G"
            virtio1:
              pool: local-lvm
              definition: "50,format=raw"
          cores: 4
          memory: 2048
          description:
            groups:
              - vm
              - nfs
              - ipaclients
            host_vars:
              ansible_ssh_private_key_file: "./keys/nfs/id_rsa"
        cloudinit:
          drive_device: ide2
          userdata: |
            #cloud-config
            users:
              - name: netsoc
                gecos: Netsoc Management User
                primary_group: netsoc
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - {{ lookup('file', './keys/nfs/id_rsa.pub') }}
            preserve_hostname: false
            manage_etc_hosts: true
            fqdn: nfs.vm.netsoc.co
          networkconfig: 
            version: 2
            ethernets:
              ens18: "{{ interfaces.nfs.net0 }}"
        wait_for_ssh_ip: "{{ interfaces.nfs.net0.addresses[0] }}"
  vars_files:
    - vars/network.yml
    - vars/proxmox.yml
    - vars/secrets.yml

- name: "Reload inventory to pull new VMs"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - meta: refresh_inventory
