---

- name: "Ensure Docker Nodes"
  hosts: proxmox_hosts
  roles:
    # Manager VM
    - role: proxmox-infra-cloudinit-vm
      when: "ansible_play_hosts_all.index(inventory_hostname) < 3"
      vars:
        vm:
          name: "manager{{ ansible_play_hosts_all.index(inventory_hostname) }}.vm.netsoc.co"
          clone: "netsoc-ubuntu-server-{{ inventory_hostname }}"
          description:
            groups:
              - vm
              - docker_swarm
              - docker_swarm_managers
              - ipaclients
            host_vars:
              ansible_ssh_private_key_file: "./keys/docker_swarm/id_rsa"
          net:
            net0: "virtio,bridge=vmbr0,tag=30"
          disks:
            virtio0:
              resize: "30G"
          cores: 4
          memory: 4096
        cloudinit:
          drive_device: ide2
          userdata: |
            #cloud-config
            users:
              - name: netsoc
                gecos: Netsoc Management User
                primary_group: netsoc
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - "{{ lookup('file', './keys/docker_swarm/id_rsa.pub') }}"
            preserve_hostname: false
            manage_etc_hosts: true
            fqdn: manager{{ ansible_play_hosts_all.index(inventory_hostname) }}.vm.netsoc.co
          networkconfig:
            version: 2
            ethernets:
              ens18:
                addresses:
                  - "{{ interfaces.managerN.net0.addresses[0] | ipmath(ansible_play_hosts_all.index(inventory_hostname)) }}/24"
                gateway4: "{{ interfaces.managerN.net0.gateway4 }}"
                nameservers: "{{ interfaces.managerN.net0.nameservers }}"
                optional: true
        wait_for_ssh_ip: "{{ interfaces.managerN.net0.addresses[0]  }}"
    # Worker VM
    - role: proxmox-infra-cloudinit-vm
      when: "ansible_play_hosts_all.index(inventory_hostname) > 3"
      vars:
        vm:
          name: "worker{{ ansible_play_hosts_all.index(inventory_hostname) }}.vm.netsoc.co"
          clone: "netsoc-ubuntu-server-{{ inventory_hostname }}"
          description: 
            groups:
              - vm
              - docker_swarm
              - docker_workers
            vars:
              ansible_ssh_private_key_file: "./keys/docker_swarm/id_rsa"
          net:
            net0: "virtio,bridge=vmbr0,tag=30"
          resize_disks:
            virtio0: "20G"
          cores: 4
          memory: 4096
        cloudinit:
          cloudinit_device: ide2
          userdata: |
            #cloud-config
            users:
              - name: netsoc
                gecos: Netsoc Management User
                primary_group: netsoc
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - "{{ lookup('file', './keys/docker_swarm/id_rsa.pub') }}"
            preserve_hostname: false
            manage_etc_hosts: true
            fqdn: worker{{ ansible_play_hosts_all.index(inventory_hostname) }}.vm.netsoc.co
          networkconfig:
            version: 2
            ethernets:
              ens18:
                addresses:
                  - "{{ interfaces.workerN.net0.addresses[0] | ipmath(ansible_play_hosts_all.index(inventory_hostname)) }}/24"
                gateway4: "{{ interfaces.workerN.net0.gateway4 }}"
                nameservers: "{{ interfaces.workerN.net0.nameservers }}"
                optional: true
        wait_for_ssh_ip: "{{ interfaces.workerN.net0.addresses[0] }}"
  vars_files:
    - vars/network.yml
    - vars/proxmox.yml
    - vars/secrets.yml

- name: "Reload inventory to pull new VMs"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - meta: refresh_inventory