---
- name: "Ensure Docker n Co"
  hosts: non_sudo
  roles:
  - docker

- name: "Ensure Docker Swarm created" 
  hosts: swarm_creators
  roles:
    - docker-swarm-create
  tags:
    - install-base
    - install-swarm

- name: "Ensure Docker Swarm managers enrolled"
  hosts: swarm_managers
  roles:
    - docker-swarm-enroll-manager
  vars:
    swarm_creator: "{{ groups['swarm_creators'][0] }}"
  tags:
    - install-base
    - install-swarm

- name: "Ensure Docker Swarm workers enrolled"
  hosts: swarm_workers
  roles:
    - docker-swarm-enroll-worker
  vars:
    swarm_creator: "{{ groups['swarm_creators'][0] }}"
  tags:
    - install-base
    - install-swarm