---
- name: Ensure Consul settings set
  hosts: swarm_creators
  vars_files:
    - vars/netsocbot.yml
    - vars/consul.yml
    - vars/secrets_legacy.yml
  tasks:
    - include: roles/netsocbot/tasks/consul_conf.yml
  tags:
    - consul

- name: Deploy Netsoc Discord Bot
  hosts: swarm_creators
  vars_files:
    - vars/netsocbot.yml
    - vars/email.yml
    - vars/secrets_legacy.yml
  roles: 
    - netsocbot
  tags:
    - bot
