---
- name: "Initial setup"
  hosts: portal.infra.netsoc.co
  roles:
    - ansible-requirements
    - utf8-locale
  tags:
    - initial

- name: "Enroll in IPA server"
  hosts: portal.infra.netsoc.co
  roles:
    - role: ipa-client-enroll
      vars:
        client:
          addresses:
            - "{{ ansible_default_ipv4.address }}"
  vars_files:
    - "vars/network.yml"
    - "vars/secrets_mapping.yml"
    - "vars/secrets.yml"
  tags:
    - ipa-client-enroll

- name: Setup server MOTD
  hosts: portal.infra.netsoc.co
  tasks:
    - become: yes
      copy:
        content: "{{ lookup('file', './portal-banner.txt') }}"
        dest: /etc/netsoc-banner
    - become: yes
      copy:
        content: "{{ lookup('file', './portal-motd.txt') }}"
        dest: /etc/netsoc-motd
    - become: yes
      shell: /bin/rm -rf /etc/update-motd.d/*
    - become: yes
      copy:
        content: |
          #!/bin/sh
          cat /etc/netsoc-motd
        mode: "0755"
        dest: /etc/update-motd.d/00-netsoc-motd
    - become: yes
      copy:
        content: ""
        dest: /etc/legal
    - become: yes
      lineinfile:
        regex: "^#PrintLastLog"
        line: "PrintLastLog no"
        path: /etc/ssh/sshd_config
    - become: yes
      lineinfile:
        regex: "^#Banner none"
        line: "Banner /etc/netsoc-banner"
        path: /etc/ssh/sshd_config
    - become: yes 
      copy:
        content: | # print newline after motd dump, looks cleaner
          printf "\n"
        dest: /etc/profile.d/netsoc-newline.sh
    - become: yes
      service:
        name: sshd
        state: restarted
  tags:
    - provision

- name: "Ensure SSH Password Auth is enabled"
  hosts: portal.infra.netsoc.co
  become: yes
  tasks:
    - name: "Edit sshd_config"
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^.*PasswordAuthentication.*$'
        replace: 'PasswordAuthentication yes'
    - name: "Restart sshd"
      systemd:
        name: sshd
        state: reloaded
  tags:
    - provision