---
- name: "Initial setup"
  hosts: gluster_server
  roles:
    - ansible-requirements
    - utf8-locale
  tags:
    - initial

- name: "Enroll in IPA server"
  hosts: gluster_server
  roles:
    - role: freeipa-client
      vars:
        client:
          addresses:
            - "{{ ansible_default_ipv4.address }}"
  vars_files:
    - "vars/freeipa.yml"
    - "vars/network.yml"
    - "vars/secrets.yml"
  tags:
    - ipa

- name: "Setup Data Disk"
  hosts: gluster_server
  become: yes
  tasks:
    - name: "Create LVM volume group"
      lvg:
        pvs:
          - /dev/vdb
        state: present
        vg: brickvg

    - name: "Check datavolume exists"
      stat:
        path: '/dev/mapper/brickvg-thinpool'
      ignore_errors: true
      register: _volume

    - name: "Create data volume"
      lvol:
        lv: 'thinpool'
        size: '90%VG'
        vg: 'brickvg'
        force: yes
      register: _datavolume_created
      when: not _volume.stat.exists

    - name: "Create metadata volume"
      lvol:
        lv: 'thinpool-meta'
        size: '2%VG'
        vg: 'brickvg'
      when: _datavolume_created.changed

    - name: "Convert data volume to thin pool one"
      shell:
        lvconvert
          --type thin-pool
          --poolmetadata "brickvg/thinpool-meta"
          "brickvg/thinpool"
          -y
          -c 512K
      when: _datavolume_created.changed
    - filesystem:
        fstype: xfs
        dev: /dev/mapper/brickvg-thinpool
        opts: -f -i size=512 -n size=8192 -d su=128k,sw=10
      when: _datavolume_created.changed
    - name: Ensure Gluster brick and mount directories exist.
      file:
        path: /mnt/data-disk
        state: directory
        mode: 0755
    - mount:
        path: /mnt/data-disk
        src: /dev/brickvg/thinpool
        fstype: xfs
        opts: rw,inode64,noatime,nouuid
        state: mounted
  tags:
    - data-disk

- name: Setup GlusterFS volumes
  hosts: gluster_server
  become: yes
  roles:
    - geerlingguy.glusterfs
  tasks:
    - name: Configure Gluster volume
      gluster_volume:
        state: present
        name: "{{ item.name }}"
        brick: "{{ gluster_brick_dir }}/{{ item.name }}"
        replicas: "{{ groups.gluster_server | length }}"
        cluster: "{{ groups.gluster_server | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true
      with_items: "{{ gluster_volumes }}"
  vars:
    gluster_volumes:
      - { name: storage }
      - { name: homedirs }
    gluster_brick_dir: "/mnt/data-disk"

# https://www.redhat.com/en/blog/hardening-gluster-installations-tls
- name: "Setup TLS/SSL Private Key & Cert"
  hosts: gluster
  become: yes
  tasks:
    - shell: |
        openssl genrsa -out /etc/ssl/glusterfs.key 4096 &&
        openssl req -new -x509 -key /etc/ssl/glusterfs.key -subj "/CN={{ ansible_fqdn }}" -out /etc/ssl/glusterfs.pem
      args:
        executable: /bin/bash
    - slurp:
        src: /etc/ssl/glusterfs.pem
      register: host_pem_slurped
    - set_fact:
        host_pem: "{{ host_pem_slurped['content'] | b64decode }}"
    - debug:
        msg: "{{ host_pem }}"

- name: "Setup self-signed CA"
  hosts: gluster
  become: yes
  tasks:
    - set_fact:
        ca: |
          {{ ( play_hosts | map('extract',hostvars) |
             selectattr('host_pem','defined') |
             map(attribute='host_pem') | list) | join('') }}
    - debug:
        msg: "{{ ca }}"
    - copy:
        content: "{{ ca }}"
        dest: "/etc/ssl/glusterfs.ca"

- name: "Start TLS/SSL and mount volumes"
  hosts: gluster
  become: yes
  tasks:
    - shell: | 
        echo "y" | gluster volume stop {{ item.name }} || true
        gluster volume set {{ item.name }} client.ssl on
        gluster volume set {{ item.name }} server.ssl on
        gluster volume set {{ item.name }} auth.ssl-allow {{ groups[item.group] | join(',') }}
        gluster volume set {{ item.name }} ssl.cipher-list 'HIGH:!SSLv2'
        gluster volume start {{ item.name }}
      args:
        executable: /bin/bash
      when: "inventory_hostname in groups.gluster_server"
      with_items: "{{ gluster_volumes }}"
      run_once: true 
    - shell:
        touch /var/lib/glusterd/secure-access
    - name: Ensure Gluster brick and mount directories exist.
      file: "path={{ item.mount }} state=directory mode=0775"
      with_items: "{{ gluster_volumes }}"
    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ item.mount }}"
        src: "{{ groups.gluster_server[0] }}:/{{ item.name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
      with_items: "{{ gluster_volumes }}"
  vars:
    gluster_volumes: 
      - { name: "storage", mount: "/storage", group: "gluster_client_allowed_mount_storage" }
      - { name: "homedirs", mount: "/home/users", group: "gluster_client_allowed_mount_homedirs" }
