---
- name: "Initial setup"
  hosts: games
  become: yes
  roles:
    - ansible-requirements
    - utf8-locale
    - docker
  tags:
    - initial

- name: "Enroll in IPA server"
  hosts: games
  roles:
    - role: freeipa-client
      vars:
        client:
          addresses:
            - "{{ ansible_default_ipv4.address }}"
  vars_files:
    - "vars/freeipa.yml"
    - "vars/network.yml"
    - "vars/secrets.yml"

- name: "Setup Data Disk"
  hosts: games
  roles:
    - role: simple-disk
      vars:
        device: "/dev/vdb"
        partition_size: "100%"
        fstype: "ext4"
        mount_path: "/mnt/data-disk"
        mount_opts: "rw"

- name: Ensure Minecraft Server
  hosts: games
  roles:
    - role: minecraft
      vars:
        mount: "/mnt/data-disk/minecraft"
    
