- name: "Enroll in IPA server"
  hosts: web
  roles:
    - role: freeipa-client
      vars:
        client:
          addresses:
            - "{{ ansible_default_ipv4.address }}"
  vars_files:
    - "vars/freeipa.yml"
    - "vars/network.yml"
    - "vars/secrets.yml"

- name: Setup NFS client and NFS mount requirements
  hosts: web
  roles:
    - role: nfs-client-requirements
    - role: autofs-automount
      vars:
        src: nfs.vm.netsoc.co:/
        mount: /home/users
        opts: fstype=nfs4,rw,vers=4.2,sec=sys,hard,bg
  vars_files:
    - "vars/idmap.yml"
    - "vars/freeipa.yml"
    - "vars/secrets.yml"

- name: "Ensure Nginx Unit"
  hosts: web
  tasks:
    - docker_volume:
        name: unit_shared_sock
    - docker_container:
        name: unit
        entrypoint: /usr/sbin/unitd --no-daemon --control unix:/var/run/control.unit.sock --user www-data --group www-data
        image: nginx/unit:1.18.0-full
        privileged: yes
        restart_policy: always
        volumes:
          - "./home/users/:/home/users/:Z"
          - "unit_shared_sock:/var/run/"

