- name: Setup
  become: yes
  hosts: control
  tasks:
    - name: Random number to avoid collisions
      set_fact:
        images_uuid: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
    - name: Make /tmp/images/{{images_uuid}} dir
      file:
        state: directory
        path: "/tmp/images/{{ images_uuid }}"
  tags:
    - always

- name: Images
  hosts: control
  become: yes
  tasks:
    - block:
      - set_fact:
          image_output: "/tmp/images/{{ images_uuid }}/"
      - include_role:
          name: cloud-lxc-images
  ignore_errors: yes
  tags:
    - always

- name: Copy Images to Proxmox Hosts
  become: yes
  hosts: proxmox_hosts
  tasks:
    - name: Copy images
      synchronize:
        src: "{{ hostvars['control']['image_output'] }}/"
        dest: "/var/lib/vz/template/cache/"
  tags:
    - always

- name: Cleanup
  become: yes
  hosts: control
  tasks:
    - name: Tidy up directory
      file:
        path: "/tmp/images/{{ images_uuid }}"
        state: absent
  tags:
   - always