---

- name: "IPA - Set Internal DNS records"
  hosts: auth.infra.netsoc.co
  tasks:
    - ipa_dnsrecord:
        zone_name: "{{ ipa.domain }}"
        record_name: "{{ item.name }}"
        record_type: "{{ item.type }}"
        record_value: "{{ item.value }}"
        ipa_host: "{{ ipa.server }}"
        ipa_pass: "{{ ipa.admin_password }}"
        state: "{{ item.state is defined and item.state or 'present' }}"
      with_items:
        # Unlike the external dns playbook, this playbook does not manage all DNS records
        # If you make a record and remove it here without state:absent, you will need to manually remove it from 
        # the FreeIPA WebUI.
        # To remove it here, add state: absent to the record in the table below
        - { type: A, name: "pg.databases",         value: "{{ interfaces.infra.databases.net0.addresses[0] | ipaddr('address') }}" }
        - { type: A, name: "mysql.databases",      value: "{{ interfaces.infra.databases.net0.addresses[0] | ipaddr('address') }}" }
        - { type: A, name: "prometheus.databases", value: "{{ interfaces.infra.databases.net0.addresses[0] | ipaddr('address') }}" }
  vars_files:
    - vars/network.yml
    - vars/secrets_mapping.yml
    - vars/secrets.yml
  tags:
    - dns
