---
- name: "Initial setup"
  hosts: portal
  roles:
    - ansible-requirements
    - docker
    - utf8-locale
  tags:
    - initial

- name: "Enroll in IPA server"
  hosts: portal
  roles:
    - role: freeipa-client
      vars:
        client:
          addresses:
            - "{{ ansible_default_ipv4.address }}"
  vars_files:
    - "vars/freeipa.yml"
    - "vars/network.yml"
    - "vars/secrets.yml"
  tags:
    - ipa

- name: Setup server MOTD
  hosts: portal
  tasks:
    - become: yes
      copy:
        content: "{{ lookup('file', './portal-banner.txt') }}"
        dest: /etc/netsoc-banner
    - become: yes
      copy:
        content: "{{ lookup('file', './portal-motd.txt') }}"
        dest: /etc/netsoc-motd
    - become: yes
      shell: /bin/rm -rf /etc/update-motd.d/*
    - become: yes
      copy:
        content: |
          #!/bin/sh
          cat /etc/netsoc-motd
        mode: "0755"
        dest: /etc/update-motd.d/00-netsoc-motd
    - become: yes
      copy:
        content: ""
        dest: /etc/legal
    - become: yes
      lineinfile:
        regex: "^#PrintLastLog"
        line: "PrintLastLog no"
        path: /etc/ssh/sshd_config
    - become: yes
      lineinfile:
        regex: "^#Banner none"
        line: "Banner /etc/netsoc-banner"
        path: /etc/ssh/sshd_config
    - become: yes 
      copy:
        content: | # print newline after motd dump, looks cleaner
          printf "\n"
        dest: /etc/profile.d/netsoc-newline.sh
    - become: yes
      service:
        name: sshd
        state: restarted

- name: "Ensure Nginx Unit + Unit Proxy"
  hosts: portal
  become: yes
  tasks:
    - docker_volume:
        name: unit_shared_sock
    - docker_container:
        name: unit
        entrypoint: /usr/sbin/unitd --no-daemon --control unix:/var/run/control.unit.sock --user www-data --group www-data
        image: nginx/unit:1.19.0-full
        privileged: yes
        restart_policy: always
        volumes:
          - "/home/users/:/home/users/:z"
          - "unit_shared_sock:/var/run/:z"
    - file:
        path: /root/unit
        state: directory
    - copy:
        content: |
          chmod 777 /var/run/control.unit.sock
        dest: /root/unit/fix-socket-permissions.sh
        mode: 
    - copy: 
        content: |
          server {
            auth_basic           "pass pls";
            auth_basic_user_file "/proxy.htpasswd"; 
            listen 0.0.0.0:8080;
            location / {
              proxy_pass http://unix:/var/run/control.unit.sock:/;
            }
          }
        dest: /root/unit/nginx.conf
        mode: 0755
    - copy:
        dest: /root/unit/proxy.htpasswd
        content: |
          {{ unit.proxy.htpasswd }}
        owner: 101 # see User and group id https://hub.docker.com/_/nginx
        group: 101 
        mode: 0640
    - docker_container:
        name: unit_proxy
        image: nginx:1.19.2
        restart_policy: always
        ports:
          - "0.0.0.0:1023:8080"
        volumes:
          - "/root/unit/nginx.conf:/etc/nginx/conf.d/default.conf"
          - "/root/unit/proxy.htpasswd:/proxy.htpasswd:ro"
          - "/root/unit/fix-socket-permissions.sh:/docker-entrypoint.d/fix-socket-permssions.sh"
          - "unit_shared_sock:/var/run/:z"
  vars_files:
    - "vars/unit.yml"
    - "vars/secrets.yml"
