---

- name: PROMTAIL
  hosts: promtail_syslog
  become: yes
  tasks:
    - name : PROMTAIL - Set config
      copy:
        dest: /netsoc/promtail.yml 
        mode: 0777
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 0

          positions:
            filename: /tmp/positions.yaml

          clients:
            - url: http://{{ interfaces.infra.web.net1.addresses[0] | ipaddr('address') }}:3100/loki/api/v1/push

          scrape_configs:
          - job_name: system
            static_configs:
            - targets:
                - localhost
              labels:
                job: "syslog-{{ inventory_hostname }}"
                __path__: /var/log/syslog
    
    - name: PROMTAIL - Download promtail
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.0.0/promtail-linux-amd64.zip
        dest: /tmp/promtail.zip
        mode: 0777

  vars_files:
    - vars/secrets_mapping.yml
    - vars/secrets.yml
    - vars/network.yml
