- name: "Ensure Docker Swarm services"
  hosts: docker_managers
  roles:
    - role: traefik
      vars:
        dashboard_domain: traefik.netsoc.dev
        dynamic_config_mount: 
          driver_opts:
            type: "nfs"
            o: "addr=10.0.30.30,nolock,soft,rw,sec=krb5p" # ipmath(0) removes the subnet /24 at the end of the ip
            device: ":/nfs/docker/traefik/"
        config:
          log:
            level: DEBUG
          accessLog: {}
          entrypoints:
            web:
              address: ':80'
            web-secure:
              address: ':443'
          serversTransport:
            insecureSkipVerify: true
          certificatesResolvers:
            letsencrypt:
              acme:
                email: netsoc@uccsocieties.ie
                storage: /traefik/acme.json
                dnsChallenge:
                  provider: cloudflare
                  delayBeforeCheck: 0
          providers:
            file:
              directory: /traefik/dynamic_config/
              watch: true
            docker:
              swarmMode: true
              exposedByDefault: false
          api:
            dashboard: true
            insecure: true
  vars_files:
    - vars/ip_allocation.yml
    - vars/cloudflare.yml
    - vars/secrets.yml
