# Setup Traefik
- name: "Ensure Traefik directory and file config"
  hosts: docker_swarm_managers[0]
  tasks:
    - name: Ensure Traefik file config dir on NFS
      become: yes
      file:
        path: "{{ item }}"
        mode: '0770'
        state: directory
      with_items: # do not use recurse: yes because the /storage mount could have failed
        - /storage/docker/traefik
        - /storage/docker/traefik/file_config

    - set_fact:
        file_config:
          http:
            routers:
              ipa:
                entrypoints:
                  - web-secure
                rule: Host(`ipa.netsoc.dev`)
                middlewares:
                  - ipa-rewrite
                service: ipa
                tls:
                  certResolver: letsencrypt
              keycloak:
                entrypoints:
                  - web-secure
                rule: Host(`keycloak.netsoc.dev`)
                service: keycloak
                tls:
                  certResolver: letsencrypt
              discord-router:
                entrypoints:
                  - web-secure
                rule: Host(`discord.netsoc.co`)
                middlewares:
                  - discord-redirect
                service: unused
                tls:
                  certResolver: letsencrypt
              esports-router:
                entrypoints:
                  - web-secure
                rule: Host(`esports.netsoc.co`)
                middlewares:
                  - esports-redirect
                service: unused
                tls:
                  certResolver: letsencrypt

            middlewares:
              discord-redirect:
                redirectRegex:
                  regex: ^(.*)
                  replacement: 'https://discordapp.com/invite/qPUmuYw'
              esports-redirect:
                redirectRegex:
                  regex: ^(.*)
                  replacement: 'https://discordapp.com/invite/pDUv6Uj'
              ipa-rewrite:
                headers:
                  customRequestHeaders:
                    Host: ipa.vm.netsoc.co
                    Referer: https://ipa.vm.netsoc.co/ipa/
            services:
              ipa:
                loadBalancer:
                  servers:
                    - url: "https://auth.vm.netsoc.co"
              keycloak:
                loadBalancer:
                  servers:
                    - url: "http://auth.vm.netsoc.co:8080"
              unused:
                loadBalancer:
                  servers:
                    - url: 'https://google.com'

    - name: Write Traefik config
      become: yes
      copy:
        content: "{{ file_config | from_yaml }}"
        dest: /storage/docker/traefik/file_config/config.yml
        
- name: "Ensure Traefik loadbalancer running"
  hosts: docker_swarm_managers[0]
  roles:
    - role: traefik-proxmox
      vars:
        mount: "/storage/docker/traefik"
        dashboard_domain: traefik.netsoc.dev
        dashboard_basicauth: netsoc:$$2y$$05$$1Rro44k9JKujdml4I.JAe.tx2iQEnKj4ykoD3Q50Adk5Q.lOu1CsG
        config:
          log:
            level: DEBUG
          accessLog: {}
          entrypoints:
            web:
              address: ':80'
            web-secure:
              address: ':443'
          serversTransport:
            insecureSkipVerify: true
          certificatesResolvers:
            letsencrypt:
              acme:
                email: netsoc@uccsocieties.ie
                storage: /traefik/acme.json
                dnsChallenge:
                  provider: cloudflare
                  delayBeforeCheck: 0
          providers:
            file:
              directory: /traefik/file_config/
              watch: true
            docker:
              swarmMode: true
              exposedByDefault: false
          api:
            dashboard: true
            insecure: true
  vars_files:
    - vars/network.yml
    - vars/cloudflare.yml
    - vars/secrets.yml

- name: "Ensure Portainer config dir"
  hosts: docker_swarm_managers[0]
  tasks:
    - name: Ensure Portainer config dir on NFS
      become: yes
      file:
        path: "{{ item }}"
        mode: '0755'
        state: directory
      with_items:
        - /storage/docker/portainer
  
- name: "Ensure Portainer"
  hosts: docker_swarm_managers[0]
  roles:
    - name: portainer
      vars:
        mount: /storage/docker/portainer
  vars_files:
    - vars/portainer.yml
    - vars/secrets.yml

- name: "Ensure Netsoc Static Services"
  hosts: docker_swarm_managers[0]
  roles:
    - netsoc.co
    - blog.netsoc.co

- name: "Create user and database for wiki.js"
  hosts: databases
  become: yes
  tasks:
    - postgresql_db:
        name: "{{ wikijs.postgres.db }}"
        state: present
        login_host: "{{ postgres.infra.host }}"
        login_password: "{{ postgres.infra.postgres_password }}"
    - postgresql_user:
        name: "{{ wikijs.postgres.username }}"
        password: "{{ wikijs.postgres.password }}"
        login_host: "{{ postgres.infra.host }}"
        login_password: "{{ postgres.infra.postgres_password }}"
    - postgresql_privs:
        db: "{{ wikijs.postgres.db }}"
        role: "{{ wikijs.postgres.username }}"
        objs: ALL_IN_SCHEMA
        privs: SELECT,INSERT,UPDATE,DELETE
        login_host: "{{ postgres.infra.host }}"
        login_password: "{{ postgres.infra.postgres_password }}"
  vars_files:
    - vars/postgres.yml
    - vars/wikijs.yml
    - vars/secrets.yml
      
- name: "Create wiki.js"
  hosts: docker_swarm_managers[0]
  roles:
    - role: wikijs
      vars:
        postgres:
          host: "{{ postgres.infra.host }}"
  vars_files:
    - vars/postgres.yml
    - vars/wikijs.yml
    - vars/secrets.yml


