---
- name: MINECRAFT - INITIAL SETUP
  hosts: minecraft.infra.netsoc.co
  become: yes
  roles:
    - ansible-requirements
    - utf8-locale
    - docker
  tags:
    - init

- name: MINECRAFT - SETUP SERVER
  hosts: minecraft.infra.netsoc.co
  become: yes
  tasks:
    - name: Rember Manifest Map
      set_fact:
        manifest: "{{ lookup('file', '{{ playbook_dir }}/roles/minecraft/files/manifest.json') | from_json }}"
      tags:
        - server

    - name: Ensure directories exist
      file:
        path: '/{{ item }}'
        owner: root
        group: root
        mode: '0777'
        state: directory
      with_items:
        - data
        - 'data/mods'
        - world
        - 'world/serverconfig'

    - name: Ensure server config
      copy:
        src: '{{ playbook_dir }}/roles/minecraft/files/serverconfig/prometheus_exporter-server.toml'
        dest: /data/world/serverconfig/prometheus_exporter-server.toml

    - name: Ensure server icon
      copy:
        src: '{{ playbook_dir }}/roles/minecraft/files/server-icon.png'
        dest: /data/server-icon.png

    - name: Ensure server.properties
      copy:
        src: '{{ playbook_dir }}/roles/minecraft/files/server.properties'
        dest: /data/server.properties

    - name: Download Mods
      get_url:
        dest: '/data/mods'
        url: "{{ lookup('url', 'https://addons-ecs.forgesvc.net/api/v2/addon/{{item.projectID}}/file/{{item.fileID}}/download-url') | replace(' ', '%20') }}"
        force: no
      loop: '{{ manifest.files }}'

    - name: Remember Compose definition
      set_fact:
        minecraft_definition:
          version: '3.8'
          services:
            minecraft:
              container_name: minecraft
              image: itzg/minecraft-server:java8-openj9
              ports:
                - '1194:25565/tcp'
                - '19565:19565'
              restart: always
              volumes:
                - '/data:/data'
              environment:
                EULA: 'TRUE'
                TYPE: FORGE
                MEMORY: 10G
                VERSION: '{{ manifest.minecraft.version }}'
      tags:
        - server

    - name: Setup compose
      docker_compose:
        project_name: minecraft
        recreate: always
        restarted: yes
        pull: yes
        remove_orphans: yes
        state: present
        definition: '{{ minecraft_definition }}'
      tags:
        - server
  tags:
    - minecraft
