
- name: "Deploy Pterodactyl"
  hosts: lovelace
  roles:
    - pterodactyl
  vars_files:
    - vars/pterodactyl.yml
    - vars/secrets.yml
  tags:
    - install-base
    - install-swarm
    - install-swarm-services
    - lovelace
