- name: "Ensure backup job on each proxmox host"
  hosts: proxmox_hosts
  roles: backups
  vars:
    backup_hour: "3" # Backups everyday at 3am
    blacklist: "router.vm.netsoc.co"
    compress: "lzo"
    gdrive_client_id: "{{ vault_gdrive_client_id }}"
    gdrive_client_secret: "{{ vault_gdrive_client_secret }}"
    gdrive_username: "{{ vault_gdrive_username }}"
    gdrive_location: "{{ vault_gdrive_location }}"
    discord_webhook_url: "{{ vault_webook_url }}"