- name: Ensure ansible and provisioning requirements on proxmox host
  hosts: localhost
  connection: localhost
  gather_facts: no
  roles:
    - ansible
    - ifupdown2
    - packer
    - jq  # for manipulating the proxmox api pvesh when it was --output-format=json 
  # TODO(ocanty) - automate me
  # tasks:
  #   - name: Setup /etc/network/interfaces
  #     copy:
  #       content: |
  #         source /etc/network/interfaces.d/*

  #         auto lo
  #         iface lo inet loopback

  #         iface enp6s0 inet manual

  #         iface enp4s0 inet manual

  #         iface ens3f0 inet manual

  #         iface ens3f1 inet manual

  #         auto vmbr0
  #         iface vmbr0 inet manual
  #                 bridge-ports enp6s0
  #                 bridge-stp off
  #                 bridge-fd 0
  #                 bridge-vlan-aware yes
  #                 bridge-vids 2-4094

  #         auto vmbr0.10
  #         iface vmbr0.10 inet static
  #                 address 10.0.10.53/24

  #         auto vmbr0.20
  #         iface vmbr0.20 inet static
  #                 address 10.0.20.53/24
  #                 gateway 10.0.20.1

  #         auto vmbr0.30
  #         iface vmbr0.30 inet static
  #                 address 10.0.30.53/24

  #         auto vmbr0.80
  #         iface vmbr0.80 inet static
  #                 address 10.0.80.53/24

  #         auto vmbr0.90
  #         iface vmbr0.90 inet static
  #                 address 10.0.90.3/24

  #         auto vmbr0.40
  #         iface vmbr0.40 inet static
  #                 address 10.0.40.53/24

    - role: packer-provisioning-dhcp-bridge
      vars:
        bridge_inteface: "vmbr1"
        bridge_address: "10.0.100.1"
        bridge_netmask: "24"
        nat_interface: "vmbr0.20"
        dhcp_range_begin: "10.0.100.2"
        dhcp_range_end: "10.0.100.254"
        dhcp_netmask: "255.255.255.0"
        dhcp_lease_length: "24h"
        dhcp_dns_servers: "8.8.8.8,8.8.4.4"