---

- name: Ensure Postgres dir
  become: yes
  file:
    path: "{{ mount }}/"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install psycopg2 (needed for ansible pg driver)
  become: yes
  apt:
    name: python3-psycopg2
    state: present

- name: Ensure Postgres server container
  become: yes
  docker_container:
    name: "{{ container_name }}"
    state: started
    recreate: yes
    image: postgres:12.3
    restart_policy: on-failure
    env:
      POSTGRES_PASSWORD: "{{ root_password }}"
    volumes:
      - "{{ mount }}/:/var/lib/postgresql/data"
    ports:
      - "{{ ip }}:{{ port | default(5432) }}:5432"