---
- name: Ensure Consul server directories for data
  become: yes
  file:
    path: '/mnt/data-disk/consul'
    owner: netsoc
    group: 1000
    mode: 0770
    state: directory
  tags:
    - server    