-  
  ufw:
    become: yes
    rule: allow
    port: "9999"
    proto: tcp
    src: "{{ prom_server }}"
-
  ufw:
    become: yes
    rule: allow
    port: "9999"
    proto: tcp
    direction: in
    interface: "docker0"
  when: "'prometheus-hosts' in group_names"
-
  ufw:
    become: yes
    rule: reject
    port: "9999"
    proto: tcp    