
- name: "Node Exporter"
  include_role:
    name: UnderGreen.prometheus-node-exporter
  vars:
    prometheus_node_exporter_enabled_collectors:
      - conntrack
      - diskstats
      - edac
      - entropy
      - filefd
      - filesystem
      - hwmon
      - ipvs
      - loadavg
      - mdadm
      - meminfo
      - netdev
      - netstat
      - sockstat
      - stat
      - time
      - uname
      - vmstat
    prometheus_node_exporter_config_flags:
      'web.listen-address': '[::1]:9100'

- name: "Apache Prometheus Exporter"
  become: yes
  when: "'prometheus_apache' in group_names"
  docker_container:
    name: prometheus_apache
    image: "lusotycoon/apache-exporter:v0.5.0"
    command: ["-scrape_uri", "http://{{ ansible_host }}/server-status/?auto"]
    state: started
    restart_policy: unless-stopped
    ports:
      - "127.0.0.1:9117:9117"

- name: "cadvisor"
  become: yes
  when: "'prometheus_docker' in group_names"
  docker_container:
    name: cadvisor
    image: "google/cadvisor:v0.28.5"
    state: started
    restart_policy: unless-stopped
    ports:
      - "127.0.0.1:9388:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"

- name: "IPMI Exporter"
  docker_container:
    name: ipmi_exporter
    image: "mloc6/ipmi_exporter"
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "127.0.0.1:9289:9289"
    devices:
      - "/dev/ipmi0"

-
  include_tasks: "exporter_exporter.yaml"
-
  include_tasks: "firewall.yaml"