---


- name: "Ensure Auth server"
  hosts: lovelace
  roles:
    - role: proxmox-infra-cloudinit-vm
      vars:
        vm:
          name: "auth.vm.netsoc.co"
          protection: no
          clone: "netsoc-ubuntu-server-{{ inventory_hostname }}"
          timeout: 300
          description: |
            groups:
              - vm
              - auth
            vars:
              ansible_ssh_private_key_file: "/root/NaC-repo/keys/auth/id_rsa"
          net:
            net0: "virtio,bridge=vmbr0,tag=30"
            net1: "virtio,bridge=vmbr0,tag=30"
          resize_disks:
            virtio0: "+5G"
          additional_disks:
            virtio1: "local-lvm:25,format=raw"
          cores: 4
          memory: 2048
        cloudinit:
          metadata: ""
          userdata: |
            #cloud-config
            users:
              - name: netsoc
                gecos: Netsoc Management User
                primary_group: netsoc
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys:
                  - {{ ssh_key_sig }}
            preserve_hostname: false
            manage_etc_hosts: true
            fqdn: auth.vm.netsoc.co
          networkconfig: |
            version: 2
            ethernets:
              30a:
                match:
                  name: ens18
                addresses:
                  - {{ ip_allocation.freeipa_base }}
                gateway4: 10.0.30.1
                nameservers:
                  search: {{ ip_allocation.search }}
                  addresses: {{ ip_allocation.nameservers }}
              30b:
                match:
                  name: ens19
                addresses:
                  - {{ ip_allocation.keycloak_base }}
                gateway4: 10.0.30.1
                nameservers:
                  search: {{ ip_allocation.search }}
                  addresses: {{ ip_allocation.nameservers }}
        wait_for_ssh: "{{ ip_allocation.freeipa_base | ipmath(ansible_play_hosts_all.index(inventory_hostname)) }}"
                
  vars:
    ssh_key_sig: "{{ lookup('file', './keys/auth/id_rsa.pub') }}"
  vars_files:
    - vars/ip_allocation.yml
    - vars/proxmox.yml
    - vars/secrets.yml

- name: "Reload inventory to pull new VMs"
  hosts: 127.0.0.1
  connection: local
  tasks:
    - meta: refresh_inventory

- import_playbook: provision-auth.yml