---
- name: "Ensure GSSAPI compatible Paramiko wheel"
  become: yes
  copy:
    src: "paramiko-2.2.1-py2.py3-none-any.whl"
    dest: "/netsoc-neo/paramiko-2.2.1-py2.py3-none-any.whl"
    owner: root
    group: root
    mode: 0770

- name: "Ensure GSSAPI compatible Paramiko fix"
  become: yes
  pip:
    name: "/netsoc-neo/paramiko-2.2.1-py2.py3-none-any.whl"
    state: forcereinstall