
- name: Ensure unarchive requirements
  apt:
    name:  unzip
    state: present

- name: Ensure Packer 1.6.5
  unarchive:
    src: https://releases.hashicorp.com/packer/1.6.5/packer_1.6.5_linux_amd64.zip
    dest: /usr/local/bin
    mode: +x
    remote_src: yes