---
- name: Ensure /etc/docker
  become: yes
  file:
    path: /etc/docker
    state: directory

- name: Ensure /etc/docker/daemon.json
  become: yes
  template:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json

- shell: yum install -y yum-utils && yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- yum:
    name:
      # remove when containerd is in rhel8
      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm
      - docker-ce
      - docker-ce-cli
    state: latest

- name: Ensure Docker Compose dependencies
  become: yes
  package:
    name: python3
    state: latest

- name: Ensure Docker Compose
  become: yes
  pip:
    name: docker-compose
    state: latest

- name: Reload Docker daemon
  become: yes
  systemd:
    state: restarted
    daemon_reload: no
    enabled: yes
    name: docker