---
- name: 'Ensure Consul Bot token'
  run_once: true
  consul_acl_prefix:
    scheme: https
    host: consul.{{ dev_site }}
    port: 443
    name: Discord Bot Token
    token_type: management
    token: '{{ consul_bot_token }}'
    mgmt_token: '{{ consul_master_token }}'
    rules:
      - key_prefix: discord/
        policy: read
- name: Ensure Consul KVs
  consul_kv:
    scheme: https
    host: consul.{{ dev_site }}
    port: 443
    key: 'discordbot/{{ item.key }}'
    value: '{{ item.value | to_json }}'
    token: '{{ consul_master_token }}'
  with_items:
    - key: channels
      value:
        public_announcements: '{{ public_announcements }}'
        private_events: '{{ private_events }}'
        public_general: '{{ public_general }}'
    - key: servers
      value:
        public: '{{ public_server }}'
        committee: '{{ committee_server }}'
    - key: welcome_messages
      value:
        - 'Welcome to the Netsoc Discord server %s! :)'
    - key: quote_blacklist
      value:
        - '294443112175108096'
        - '463659782545342465'
        - '645352469517434905'
        - '630840553227157514'
        - '684009440441008128'
