modules:
  http_2xx:
    prober: http
  harbor_health_jobservice:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "jobservice",\s+"status": "healthy"'
  harbor_health_redis:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "redis",\s+"status": "healthy"'
  harbor_health_core:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "core",\s+"status": "healthy"'
  harbor_health_database:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "database",\s+"status": "healthy"'
  harbor_health_registry:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "registry",\s+"status": "healthy"'
  harbor_health_registryctl:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "registryctl",\s+"status": "healthy"'
  harbor_health_portal:
    prober: http
    timeout: 20s
    http:
      fail_if_not_ssl: true # make sure its HTTPS
      fail_if_body_not_matches_regexp:
        - '"name": "portal",\s+"status": "healthy"'