---

- name: Ensure mysql dir
  become: yes
  file:
    path: "{{ mount }}/"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure MySQL server container
  become: yes
  docker_container:
    name: "{{ container_name }}"
    state: started
    recreate: yes
    image: mysql:8.0.20
    restart: unless-stopped
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"
    volumes:
      - "{{ mount }}/:/var/lib/mysql"
    ports:
      - "{{ ip }}:{{ port | default(3306) }}:3306"