---
- name: "Ensure pip installed"
  become: yes
  apt:
    name:
      - python-distutils-extra
      - python3-apt
      - python3-pip
    state: latest
    update_cache: yes

- name: Ensure upgraded pip and ansible pip requirements
  become: yes
  pip:
    name:
      - pip
      - jsondiff
      - pymysql # needed for ansible mysql 
    state: latest
    extra_args: --upgrade