---
- name: Ensure auditd installed
  become: yes
  apt:
    name: auditd

- name: Ensure rules file 
  become: yes
  copy:
    src: "files/audit.rules"
    dest: "/etc/audit/rules.d/audit.rules"

- name: Ensure auditd running
  become: yes
  systemd:
    state: started
    masked: no
    name: auditd
