
- set_fact:
    unique_name: "{{ wikijs.hostname | regex_replace('\\.','_') }}"

- name: Ensure wiki in Docker Swarm
  become: yes
  docker_stack:
    state: present
    name: "{{ unique_name }}"
    #with_registry_auth: true
    compose:
      - version: "3.7"
        services:
          server:
            image: requarks/wiki:2.4
            networks:
              traefik:
            environment:
              HA_ACTIVE: "1"
              DB_TYPE: "postgres"
              DB_HOST: "{{ wikijs.postgres.host }}"
              DB_PORT: "{{ wikijs.postgres.port | default(5432) }}"
              DB_USER: "{{ wikijs.postgres.username }}"
              DB_PASS: "{{ wikijs.postgres.password }}"
              DB_NAME: "{{ wikijs.postgres.db }}" 
            deploy:
              mode: global
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.{{ unique_name }}.rule=Host(`{{ wikijs.hostname }}`)"
                - "traefik.http.routers.{{ unique_name }}.entrypoints=web-secure"
                - "traefik.http.routers.{{ unique_name }}.tls.certResolver=letsencrypt"
                - "traefik.http.services.{{ unique_name }}.loadbalancer.server.port=3000"
                - "traefik.http.routers.{{ unique_name }}.service={{ unique_name }}"
                - "traefik.docker.network=traefik"
              restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
        networks:
          traefik:
              external: true
              name: traefik