{
 "title": "Discord Bot",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Discord Bot Commands",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"discord_bot_instance_1\"} | json",
     "legendFormat": "command"
    }
   ]
  },
  {
   "title": "Members Joined This Acadeic Year",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "members_joined", "legendFormat": "members_joined" }
   ]
  },
  {
   "title": "Text Channel Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "message_count{channel=\"248421213628530688\",server=\"248421213628530688\"}",
     "legendFormat": "general"
    },
    {
     "expr": "message_count{channel=\"494539080885993472\",server=\"248421213628530688\"}",
     "legendFormat": "announcements"
    },
    {
     "expr": "message_count{channel=\"691756092379627621\",server=\"248421213628530688\"}",
     "legendFormat": "corona"
    },
    {
     "expr": "message_count{channel=\"248422864062119947\",server=\"248421213628530688\"}",
     "legendFormat": "tech-chat"
    },
    {
     "expr": "message_count{channel=\"763012234636034069\",server=\"248421213628530688\"}",
     "legendFormat": "programming"
    },
    {
     "expr": "message_count{channel=\"248421871199059971\",server=\"248421213628530688\"}",
     "legendFormat": "general-gaming"
    },
    {
     "expr": "message_count{channel=\"689518089536143362\",server=\"248421213628530688\"}",
     "legendFormat": "minecraft"
    },
    {
     "expr": "message_count{channel=\"684009440441008128\",server=\"248421213628530688\"}",
     "legendFormat": "politics"
    },
    {
     "expr": "message_count{channel=\"571834322596659208\",server=\"248421213628530688\"}",
     "legendFormat": "memes"
    }
   ]
  }
 ]
}