{
 "title": "Minecraft Player Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player",
    "label": "Player",
    "query": {
     "query": "label_values(mc_player_list, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Hours Played",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(mc_player_list{name=\"$player\"}[1000d:1m])"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "mc_player_list{name=\"$player\"}",
     "legendFormat": "$player"
    }
   ]
  },
  {
   "title": "Total Playtime over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "count_over_time(mc_player_list{name=\"$player\"}[1000d:1m])",
     "legendFormat": "Total Playtime for $player"
    }
   ]
  }
 ]
}