{
 "title": "Minecraft",
 "tags": [ "public" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Concurrent Players",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(mc_player_list) ", "legendFormat": "Players Online" }
   ]
  },
  {
   "title": "Players Online Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "mc_player_list", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_bytes_max)", "legendFormat": "Max Memory" },
    { "expr": "sum(jvm_memory_bytes_used)", "legendFormat": "Memory used" },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\"}",
     "legendFormat": "Committed Memory"
    }
   ]
  },
  {
   "title": "Currently Online",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mc_player_list) or vector(0)"
    }
   ]
  },
  {
   "title": "Unique Players over last 7 days",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(mc_player_list[7d])) or vector(0)"
    }
   ]
  }
 ]
}