{
 "title": "Traefik 2 By Service",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": { "query": "label_values(job)" } },
   {
    "name": "protocol",
    "label": "Protocol:",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_open_connections, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request per $interval",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{protocol=~\"$protocol\",service=~\"$service\"}[$interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "404 Error Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",protocol=~\"$protocol\",service=~\"$service\"}[$interval]))"
    }
   ]
  },
  {
   "title": "503 Error count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"503\",protocol=~\"$protocol\",service=~\"$service\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{protocol=~\"$protocol\",service=~\"$service\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol=~\"$protocol\",service=~\"$service\"}) / sum(traefik_entrypoint_requests_total{protocol=~\"$protocol\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Bad Status Code Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",method=\"GET\",protocol=~\"$protocol\",service=~\"$service\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service\"}[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Access to services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=~\"http|https\",service=~\"$service\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "SERVICE - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{service=~\"$service\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Status Code Count ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{protocol=~\"$protocol\",service=~\"$service\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}