
#Settings affecting the logical server side.
[server]

	#Server dev opt-out settings !WARNING THE OPT-OUTs will be moved to common-config.toml in the next MC version!
	[server.optout]
		#Disable possibility to sit on stools and chairs.
		without_chair_sitting = false
		#Disable that mobs will sit on chairs and stools.
		without_mob_chair_sitting = false
		#Disable the speed boost of ladders in this mod.
		without_ladder_speed_boost = false
		#Disable history refabrication feature of the crafting table.
		without_crafting_table_history = false

	#Miscellaneous settings
	[server.miscellaneous]
		#Disable directly picking up layers from slabs and slab  slices by left clicking while looking up/down.
		without_direct_slab_pickup = false

	#Tweaks
	[server.tweaks]
		#Defines, in percent, how fast the lab furnace smelts compared to a vanilla furnace. 100% means vanilla furnace speed, 150% means the lab furnace is faster. The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 800
		furnace_smelting_speed_percent = 130
		#Defines, in percent, how fuel efficient the lab furnace is, compared to a vanilla furnace. 100% means vanilla furnace consumiton, 200% means the lab furnace needs about half the fuel of a vanilla furnace, The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 400
		furnace_fuel_efficiency_percent = 100
		#Defines the energy consumption (per tick) for speeding up the smelting process. If IE is installed, an external heater has to be inserted into an auxiliary slot of the lab furnace. The power source needs to be able to provide at least 4 times this consumption (fixed threshold value). The value can be changed on-the-fly for tuning. The default value corresponds to the IE heater consumption.
		#Range: 2 ~ 1024
		furnace_boost_energy_consumption = 24
		#Defines (as comma separated list of full registry names) which items are allowed as external heaters in the Aux slot for powered speed boosting.
		furnace_accepted_heaters = "immersiveengineering:furnace_heater"
		#Defines, in percent, how high the probability is that a mob sits on a chair when colliding with it. Can be changed on-the-fly for tuning.
		#Range: 0.0 ~ 80.0
		chair_mob_sitting_probability_percent = 10.0
		#Defines, in percent, probable it is that a mob leaves a chair when sitting on it. The 'dice is rolled' about every 20 ticks. There is also a minimum Sitting time of about 3s. The config value can be changed on-the-fly for tuning.
		#Range: 0.001 ~ 10.0
		chair_mob_standup_probability_percent = 1.0
		#Disables increasing/decreasing the crafting grid items by scrolling over the crafting result slot.
		without_crafting_mouse_scrolling = false
		#Defines how many millibuckets can be transferred (per tick) through the valves. That is technically the 'storage size' specified for blocks that want to fill fluids into the valve (the valve has no container and forward that to the output block), The value can be changed on-the-fly for tuning. 
		#Range: 1 ~ 32000
		pipevalve_max_flowrate = 1000
		#Defines how many millibuckets per redstone signal strength can be transferred per tick through the analog redstone controlled valves. Note: power 0 is always off, power 15 is always the max flow rate. Between power 1 and 14 this scaler will result in a flow = 'redstone slope' * 'current redstone power'. The value can be changed on-the-fly for tuning. 
		#Range: 1 ~ 32000
		pipevalve_redstone_gain = 20
		#Defines, in percent, how fast the electrical furnace smelts compared to a vanilla furnace. 100% means vanilla furnace speed, 150% means the electrical furnace is faster. The value can be changed on-the-fly for tuning.
		#Range: 50 ~ 800
		e_furnace_speed_percent = 290
		#Defines how much RF per tick the the electrical furnace consumed (average) for smelting. The feeders transferring items from/to adjacent have this consumption/8 for each stack transaction. The default value is only slightly higher than a furnace with an IE external heater (and no burning fuel inside).The config value can be changed on-the-fly for tuning.
		#Range: 8 ~ 4096
		e_furnace_power_consumption = 16
		#Defines if the electrical furnace automatically pulls items from an inventory at the input side.The config value can be changed on-the-fly for tuning.
		e_furnace_automatic_pulling = false
		#Defines the peak power production (at noon) of the Small Solar Panel. Note that the agerage power is much less, as no power is produced at all during the night, and the power curve is nonlinear rising/falling during the day. Bad weather conditions also decrease the production. The config value can be changed on-the-fly for tuning.
		#Range: 2 ~ 4096
		small_solar_panel_peak_production = 40
		#Defines how much RF power the Small Block Breaker requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		block_breaker_power_consumption = 64
		#Defines how much time the Small Block Breaker needs per block hardness, means: 'reluctance' * hardness + min_time, you change the 'reluctance' here.The unit is ticks/hardness. The config value can be changed on-the-fly for tuning.
		#Range: 5 ~ 50
		block_breaker_reluctance = 17
		#Defines how much time the Small Block Breaker needs at least, better said it's an offset: 'reluctance' * hardness + min_time, you change the 'min_time' here, value in ticks.The config value can be changed on-the-fly for tuning.
		#Range: 10 ~ 100
		block_breaker_min_breaking_time = 15
		#Defines if the Small Block Breaker does not work without RF power.
		block_breaker_requires_power = false
		#Defines how much RF power the Small Tree Cutter requires to magnificently increase the processing speed. The config value can be changed on-the-fly for tuning.
		#Range: 4 ~ 1024
		tree_cutter_energy_consumption = 64
		#Defines how much time the Small Tree Cutter needs to cut a tree without RF power. The value is in seconds. With energy it is 6 times faster. The config value can be changed on-the-fly for tuning.
		#Range: 10 ~ 240
		tree_cutter_cutting_time_needed = 60
		#Defines if the Small Tree Cutter does not work without RF power.
		tree_cutter_requires_power = false
		#Defines how much time the Small Milking Machine needs work. Note this is a permanent standby power, not only when the device does something. Use zero to disable energy dependency and energy handling of the machine. The config value can be changed on-the-fly for tuning.
		#Range: 0 ~ 1024
		milking_machine_energy_consumption = 0
		#Defines (for each individual cow) the minimum time between milking.
		#Range: 1000 ~ 24000
		milking_machine_milking_delay = 4000

