
#Collector settings.
[collector]
	#Enable collecting metrics about the JVM process.
	jvm = true
	#Enable collecting metrics about the Minecraft server.
	mc = true

#Web server settings.
[web]
	#The IP address to listen on. To only allow connections from the local machine, use "127.0.0.1". To allow connections from remote machines, use "0.0.0.0".
	listen_address = "0.0.0.0"
	#The TCP port to listen on. Ports 1-1023 will not work unless Minecraft is run as root which is not recommended.
	#Range: 0 ~ 65535
	listen_port = 19565

