---


- set_fact:
    unique_name: "{{ portainer.hostname | regex_replace('\\.','_') }}"

- name: Ensure mount exists with 0755
  become: yes
  file:
    path: "{{ mount }}/"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure Portainer Docker network
  become: yes
  docker_network:
    name: portainer
    driver: overlay
    attachable: yes


- name: Ensure Portainer Web UI + Agents
  become: yes
  docker_stack:
    name: "{{ unique_name }}"
    state: present
    compose:
      - version: "3.5"
        services:
          webui:
            image: portainer/portainer
            volumes:
              - "{{mount}}/:/data"
              - /var/run/docker.sock:/var/run/docker.sock
            command: -H tcp://tasks.agent:9001 --tlsskipverify
            ports:
              - target: 8000
                published: 8001
                protocol: tcp
                mode: host
              - target: 9000
                published: 9000
                protocol: tcp
                mode: host
            networks:
              portainer:
              traefik:
            deploy:
              mode: global
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.{{ unique_name }}.rule=Host(`{{ portainer.hostname }}`)"
                - "traefik.http.routers.{{ unique_name }}.entrypoints=web-secure"
                - "traefik.http.routers.{{ unique_name }}.tls.certResolver=letsencrypt"
                - "traefik.http.routers.{{ unique_name }}.service={{ unique_name }}"
                - "traefik.http.services.{{ unique_name }}.loadbalancer.server.port=9000"
                - "traefik.docker.network=traefik"
          agent:
            restart: always
            image: portainer/agent
            environment:
              AGENT_CLUSTER_ADDR: tasks.agent
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - /var/lib/docker/volumes:/var/lib/docker/volumes
            ports:
              - target: 9001
                published: 9001
                protocol: tcp
                mode: host
            networks:
              portainer:
            deploy:
              mode: global
        networks:
          traefik:
            external: true
          portainer:
            external: true
