---

- name: Ensure /netsoc-neo/docker-data/portainer exists with 0755
  become: yes
  file:
    path: /netsoc-neo/docker-data/portainer
    owner: root
    group: root
    mode: 0777
    state: directory

- name: Ensure Portainer Docker network
  become: yes
  docker_network:
    name: portainer
    driver: overlay
    attachable: yes


- name: Ensure Portainer Web UI + Agents
  become: yes
  docker_stack:
    name: portainer
    state: present
    compose:
      - version: "3.5"
        services:
          webui:
            image: portainer/portainer
            volumes:
              - /netsoc-neo/docker-data/portainer:/data
              - /var/run/docker.sock:/var/run/docker.sock
            command: -H tcp://tasks.agent:9001 --tlsskipverify
            ports:
              - target: 8000
                published: 8001
                protocol: tcp
                mode: host
              - target: 9000
                published: 9000
                protocol: tcp
                mode: host
            networks:
              portainer:
              traefik:
            deploy:
              mode: global
              placement:
                constraints:
                  - node.hostname == {{ inventory_hostname }}
              restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.portainer.rule=Host(`portainer.{{ dev_site }}`)"
                - "traefik.http.routers.portainer.entrypoints=web-secure"
                - "traefik.http.routers.portainer.tls.certResolver=letsencrypt"
                - "traefik.http.routers.portainer.service=portainer-service"
                - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
                - "traefik.docker.network=traefik"
          agent:
            restart: always
            image: portainer/agent
            environment:
              AGENT_CLUSTER_ADDR: tasks.agent
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - /var/lib/docker/volumes:/var/lib/docker/volumes
            ports:
              - target: 9001
                published: 9001
                protocol: tcp
                mode: host
            networks:
              portainer:
            deploy:
              mode: global
        networks:
          traefik:
            external: true
          portainer:
            external: true
