---
- name: Create CI Auth Token
  uri:
    url: "{{ hashivault_url }}/v1/auth/token/create"
    headers:
      X-Vault-Token: "{{ hashivault_root_token }}"
    method: POST
    body_format: json
    body:
      display_name: CI Access Token
      policies: ci
      id: "{{ hashivault_docker_registry_token }}"
      no_default_policy: true
  register: resp
  failed_when: "resp.status != 200 and resp.json != {\"errors\": [\"cannot create a token with a duplicate ID\"]}"
  tags:
    - policies  

- name: Configure CI group policy
  run_once: true
  uri:
    url: "{{ hashivault_url }}/v1/sys/policy/ci"
    headers:
      X-Vault-Token: "{{ hashivault_root_token }}"
    method: POST
    body_format: json
    status_code: [204]
    body:
      policy: "{{ lookup('file', '../files/ci_policy.hcl') }}"
  tags:
    - policies