---
- name: Get current mounted Secret Engines
  uri:
    url: "{{ hashivault_url }}/v1/sys/mounts"
    headers:
      X-Vault-Token: "{{ hashivault.root_token }}"
    method: GET
    return_content: yes
  register: engines
  tags:
    - secrets 

- name: Enable KV Engine at github/
  when: ('github/' not in engines.json)
  uri:
    url: "{{ hashivault_url }}/v1/sys/mounts/github"
    headers:
      X-Vault-Token: "{{ hashivault.root_token }}"
    method: POST
    body_format: json
    status_code: [204]
    body:
      type: kv
      version: "2"
  tags:
    - secrets

- name: Push Github secrets to Hashicorp Vault
  uri:
    url: "{{ hashivault_url }}/v1/github/personal_access_tokens"
    headers:
      X-Vault-Token: "{{ hashivault.root_token }}"
    method: PUT
    body_format: json
    status_code: [204]
    body:
      public_repo_token: "{{ hashivault.github_public_repo_pac }}"
  tags:
    - secrets 
  