---
- name: Get current mounted Secret Engines
  uri:
    url: "{{ hashivault_url }}/v1/sys/mounts"
    headers:
      X-Vault-Token: "{{ hashivault.root_token }}"
    method: GET
    return_content: yes
  register: engines
    
- name: Enable KV Engine at docker-registry/
  when: ('docker_registry/' not in engines.json)
  uri:
    url: "{{ hashivault_url }}/v1/sys/mounts/docker_registry"
    headers:
      X-Vault-Token: "{{ hashivault.root_token }}"
    method: POST
    body_format: json
    status_code: [204]
    body:
      type: kv
      version: "2"

- name: Push Docker Hub secrets to Hashicorp Vault
  uri:
    url: "{{ hashivault_url }}/v1/docker_registry/docker_hub"
    headers:
      X-Vault-Token: "{{ hashivault.root_token }}"
    method: PUT
    body_format: json
    status_code: [204]
    body:
      docker_hub_user: "{{ docker_hub.username }}"
      docker_hub_token: "{{ docker_hub.token }}"
