---
- name: "Create prometheus directory"
  become: yes
  file:
    path: "{{ prometheus_parent_dir }}/prometheus"
    mode: 0770 
    owner: nobody # Prometheus runs as nobody
    group: nogroup
    state: directory

- name: "Create prometheus/config directory"
  become: yes
  file:
    path: "{{ prometheus_parent_dir }}/prometheus/config"
    mode: 0770 
    owner: nobody
    group: nogroup
    state: directory

- name: "Create prometheus/data directory"
  become: yes
  file:
    path: "{{ prometheus_parent_dir }}/prometheus/data"
    mode: 0770 
    owner: nobody
    group: nogroup
    state: directory

- name: "Create blackbox_exporter directory"
  become: yes
  file:
    path: "{{ blackbox_exporter_parent_dir }}/blackbox_exporter"
    mode: 0770 
    owner: root
    group: root
    state: directory

- name: "Create proxmox exporter directory"
  become: yes
  file:
    path: "{{ pve_parent_dir }}/pve"
    mode: 0770 
    owner: nobody # pve exporter runs as nobody
    group: nogroup
    state: directory

- name: "Generate Prometheus config"
  become: yes
  template:
    mode: 0770
    owner: nobody
    group: nogroup
    src: "templates/prometheus.yml.j2"
    dest: "{{ prometheus_parent_dir }}/prometheus/config/prometheus.yml"
  notify:
    - restart prometheus

- name: "Generate Blackbox Exporter Config"
  become: yes
  template:
    mode: 0440
    src: "files/blackbox_exporter.yaml"
    dest: "{{ blackbox_exporter_parent_dir }}/blackbox_exporter/blackbox_exporter.yaml"
  notify:
    - restart blackbox exporter

- name: "Generate Proxmox Exporter Config"
  become: yes
  template:
    mode: 0440
    owner: nobody
    group: nogroup
    src: templates/pve.yml.j2
    dest: "{{pve_parent_dir}}/pve/pve.yml"
  notify:
    - restart pve exporter

- name: "Ensure Docker monitoring network" 
  become: yes
  docker_network:
    name: monitoring
    appends: yes

- name: "Prometheus Server"
  become: yes
  docker_container:
    name: prometheus
    networks:
      - name: monitoring
    network_mode: bridge
    purge_networks: true
    image: "prom/prometheus:v2.19.3"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=3y"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart_policy: on-failure
    restart_retries: 3
    volumes:
      - "{{ prometheus_parent_dir }}/prometheus/config:/etc/prometheus"
      - "{{ prometheus_parent_dir }}/prometheus/data:/prometheus"

- name: "Blackbox Exporter"
  become: yes
  docker_container:
    name: blackbox_exporter
    networks:
      - name: monitoring
    network_mode: bridge
    purge_networks: true
    image: "prom/blackbox-exporter:v0.17.0"
    command: "--config.file=/config/blackbox_exporter.yaml"
    restart_policy: on-failure
    restart_retries: 3
    volumes:
    - "{{ blackbox_exporter_parent_dir }}/blackbox_exporter/blackbox_exporter.yaml:/config/blackbox_exporter.yaml"

- name: "Proxmox Exporter Container"
  become: yes
  docker_container:
    image: prompve/prometheus-pve-exporter:1.3
    networks:
      - name: monitoring
    name: pve-exporter
    network_mode: bridge
    purge_networks: true
    state: started
    restart_policy: on-failure
    restart_retries: 3
    ports:
      - "9221:9221"
    volumes:
      - "{{pve_parent_dir}}/pve/pve.yml:/etc/pve.yml"