---
- name: "Create /mnt/data-disk/prometheus directory"
  become: yes
  file:
    path: /mnt/data-disk/prometheus
    mode: 0770 
    owner: root
    group: root
    state: directory

- name: "Create /mnt/data-disk/prometheus/config directory"
  become: yes
  file:
    path: /mnt/data-disk/prometheus/config
    mode: 0770 
    owner: root
    group: root
    state: directory

- name: "Create /mnt/data-disk/prometheus/data directory"
  become: yes
  file:
    path: /mnt/data-disk/prometheus/data
    mode: 0770 
    owner: root
    group: root
    state: directory

- name: "Create /mnt/data-disk/blackbox_exporter directory"
  become: yes
  file:
    path: /mnt/data-disk/blackbox_exporter
    mode: 0770 
    owner: root
    group: root
    state: directory

- name: "Generate Prometheus config"
  become: yes
  template:
    mode: 0770
    src: "templates/prometheus.yml.j2"
    dest: "/mnt/data-disk/prometheus/config/prometheus.yml"

- name: "Copy Blackbox Config"
  become: yes
  copy:
    src: "files/blackbox_exporter.yaml"
    dest: "/mnt/data-disk/blackbox_exporter/blackbox_exporter.yaml"

- name: "Ensure Docker monitoring network" 
  become: yes
  docker_network:
    name: monitoring
    appends: yes

- name: "Prometheus Server"
  become: yes
  docker_container:
    name: prometheus
    networks:
      - name: monitoring
    network_mode: bridge
    purge_networks: true
    image: "prom/prometheus:v2.19.3"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=3y"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart_policy: unless-stopped
    volumes:
      - "/mnt/data-disk/prometheus/config:/etc/prometheus"
      - "/mnt/data-disk/prometheus/data:/prometheus"

- name: "Blackbox Exporter"
  become: yes
  docker_container:
    name: blackbox_exporter
    networks:
      - name: monitoring
    network_mode: bridge
    purge_networks: true
    image: "prom/blackbox-exporter:v0.17.0"
    command: "--config.file=/config/blackbox_exporter.yaml"
    restart_policy: unless-stopped
    volumes:
    - "/mnt/data-disk/blackbox_exporter/blackbox_exporter.yaml:/config/blackbox_exporter.yaml"