---

- name: Ensure freeipa-data dir
  become: yes
  file:
    path: "{{ mount }}/freeipa-data"
    owner: root
    group: root
    # needs to 775 as this folder is accessed internally by a dirsrv user
    # https://github.com/freeipa/freeipa-container/issues/281
    mode: 0775
    state: directory

- name: Ensure freeipa-mods dir
  become: yes
  file:
    path: "{{ mount }}/freeipa-mods"
    owner: root
    group: root
    mode: 0775
    state: directory

- name: Ensure HTTP redirect disabler
  become: yes
  copy:
    src: "files/ipa-rewrite.conf"
    dest: "{{ mount }}/freeipa-mods/ipa-rewrite.conf"


- name: Ensure FreeIPA server container
  become: yes
  docker_container:
    name: freeipa_server
    state: started
    recreate: yes
    image: freeipa/freeipa-server
    command: >
      --unattended
      --realm={{ realm }}
      --domain={{ domain }}
      --ds-password={{ ds_password }}
      --admin-password={{ admin_password }}
      --setup-dns
      --forwarder=8.8.8.8
      --forward-policy=only
      --ssh-trust-dns
    restart: yes
    etc_hosts: # extra_hosts:
      '{ "{{ server_hostname }}": "{{ ip }}" }' 
    env: # environment:
      IPA_SERVER_HOSTNAME: "{{ server_hostname }}"
      IPA_SERVER_IP: "{{ ip }}"
    dns_servers:
      - 127.0.0.1
    ports:
      - "{{ ip }}:80:80"      # http
      - "{{ ip }}:443:443"    # https
      - "{{ ip }}:389:389"    # ldap
      - "{{ ip }}:636:636"    # ldaps
      - "{{ ip }}:88:88"      # kerberos
      - "{{ ip }}:464:464"    # kpasswd 
      - "{{ ip }}:749:749"    # kpasswd
      - "{{ ip }}:123:123"    # ntp
      - "{{ ip }}:53:53/tcp"  # dns
      - "{{ ip }}:53:53/udp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/etc/machine-id:/etc/machine-id"
      - "{{ mount }}/freeipa-data/:/data:Z"
    tmpfs:
      - "/run"
      - "/tmp"
    sysctls:
      # Fixes:
      # DEBUG The ipa-server-install command failed, exception: 
      # RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
      # Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
      net.ipv6.conf.lo.disable_ipv6: 0

- name: "Wait for install to finish (8-12 minutes, check {{ mount }}/freeipa-data/var/log/ipa-server-configure-first.log if time out)"
  become: yes
  wait_for:
    path: "{{ mount }}/freeipa-data/var/log/ipaserver-install.log"
    search_regex: "The ipa-server-install command was successful"
    timeout: 1200 # 20 minutes

- name: Insert trusted network ACLs 
  blockinfile:
    path: "{{ mount }}/freeipa-data/etc/named.conf"
    insertbefore: "BOF"
    marker: "# Trusted Network For Recursive DNS Queries - {mark}"
    block: |
      acl "trusted_network" {
        {{ ip | ipsubnet(24) }};
      };


- name: Modify /data/etc/named to support queries from intralan
  blockinfile:
    path: "{{ mount }}/freeipa-data/etc/named.conf"
    insertafter: "options"
    marker: "# Enable Trusted Network For Recursive DNS Queries - {mark}"
    block: |
      allow-recursion { trusted_network; };
      allow-query-cache { trusted_network; };

- name: Restart IPA
  command: docker restart freeipa_server

- name: "Wait"
  pause:
    seconds: 10