---
- name: "Ensure fail2ban installed"
  become: yes
  apt:
    name:
      - fail2ban
    state: latest
    update_cache: yes

- name: "Ensure fail2ban config customizations"
  become: yes
  copy:
    src: "files/jail.local"
    dest: "/etc/fail2ban/jail.local"

- name: "Ensure fail2ban service enabled & running"
  become: yes
  systemd:
    name: fail2ban
    enabled: true
    state: started