---
- name: Ensure Impressive
  become: yes
  docker_stack:
    state: present
    name: impressive
    compose:
      - version: '3.7'
        networks:
          traefik:
            external: true
        services:
          server:
            image: strum355/impressive
            container_name: impressive_server
            networks:
              - traefik
            deploy:
              mode: replicated
              replicas: 1
              restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.impressive.entrypoints=web-secure"
                - "traefik.http.routers.impressive.rule=Host(`impressive.{{ co_site }}`) && Method(`POST`)"
                - "traefik.http.routers.impressive.tls.certResolver=letsencrypt"
                - "traefik.http.routers.impressive.service=impressive-service"
                - "traefik.http.services.impressive-service.loadbalancer.server.port=3000"
                - "traefik.docker.network=traefik"
                - "traefik.http.routers.impressive-readme.entrypoints=web-secure"
                - "traefik.http.routers.impressive-readme.rule=Host(`impressive.{{ co_site }}`) && Method(`GET`)"
                - "traefik.http.routers.impressive-readme.service=unused-service@file"
                - "traefik.http.routers.impressive-readme.middlewares=impressive-redirect@docker"
                - "traefik.http.middlewares.impressive-redirect.redirectregex.regex=^(.*)"
                - "traefik.http.middlewares.impressive-redirect.redirectregex.replacement=https://github.com/cahalane/impressive"
                - "traefik.http.routers.impressive-readme.tls.certResolver=letsencrypt"