---
- name: "Ensure pip installed"
  become: yes
  package:
    name:
      - python3
      - python3-devel
    state: latest

- name: Ensure upgraded pip and ansible pip requirements
  become: yes
  pip:
    name:
      - pip
      - jsondiff
      - jq
    state: latest
    extra_args: --upgrade