---

- name: "Install LVM Auto Extend Script"
  become: yes
  copy:
    content: |
      #!/bin/sh
      parted ---pretend-input-tty {{ device }} resizepart {{ lvm_extended_partition }} 100% 
      parted ---pretend-input-tty {{ device }} resizepart {{ lvm_pv_partition }}  100%
      pvresize {{ device }}{{ lvm_pv_partition }}
      lvextend -r /dev/mapper/{{ lvm_vg_lv }} -l +100%FREE

    mode: u=rx,g=rx,o=r
    dest: /opt/lvm_auto_resize.sh

- name: "Install LVM Auto Extend Service"
  become: yes
  copy:
    content: |
      [Unit]
      Description=LVM Auto Extend

      [Service]
      Type=oneshot
      ExecStart=/opt/lvm_auto_resize.sh

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/lvm-auto-extend.service

- name: "Enable LVM Auto Extend Service"
  systemd:
    name: lvm-auto-extend
    enabled: yes